### ISSUE TITLE
Tag 260 / Subfield a & b conflated?

### ISSUE THREAD

**Issue by wvstolzing** [hectorcorrea/marcli#10]
marccli appears to extract _place_ information only from the MARC record pertaining to the publisher; the publisher's _name_ gets omitted.

I believe the line responsible is this:
https://github.com/hectorcorrea/marcli/blob/59f1aa9466008ce0518aa5d43f79506b4023f629/cmd/marcli/solr.go#L56

From tag 260, the function only extracts subfield a, whereas it should get b (& c) as well; because in their fathomless wisdom, the designers of the MARC system have put place info in 'a', & publisher identity in 'b'. From the ['Understanding MARC' book on the LOC website](https://www.loc.gov/marc/umb/um07to10.html):

> **260 Publication, distribution, etc.** (Imprint) (R)
> 
> _Indicator 1:_ Sequence of publishing statements
> 
> _Indicator 2: Undefined_
> 
> _Subfields used most often:_
> 
> **$a** -- Place of publication, distribution, etc. (R)  
> **$b** -- Name of publisher, distributor, etc. (R)  
> **$c** -- Date of publication, distribution, etc. (R)
> 
>   
> 
>      _Example:_    260 ## $a New York :
>                         $b Chelsea House,
>                         $c 1986.
>

**Comment by hectorcorrea** [comment]
Thanks for the detailed bug report @wvstolzing. The Solr format option is something that is not complete and I have only used it to produce the sample 'books.json` that I use on the [Solr for newbies workshop](https://github.com/hectorcorrea/solr-for-newbies). 

I wasn't expecting others to use it, since it is very opinionated on the field names, but if it is indeed useful to others I can implement the changes that you are suggesting.
