### ISSUE TITLE
Unit testing pkg/marc

### ISSUE THREAD

**Issue by blackerby** [hectorcorrea/marcli#12]
I'd like to contribute unit testing to pkg/marc. I've started working on this ([changes here](https://github.com/hectorcorrea/marcli/compare/main...blackerby:marcli:main)), but I wanted to make sure this would be a useful contribution to this project before I submit a PR.

Background: I'm in my last semester of an MLIS program and am hoping to find a job developing software in and for libraries. I've been studying Go and working on this project seems like a great way to get more familiar with MARC records and to practice writing Go.

Thanks for creating this great tool!

**Comment by hectorcorrea** [comment]
@blackerby this looks very good and I am glad that you are finding the tool useful.

I am currently not actively working on marcli and I am not sure when I will have time to look in detail and/or merge your PR if you submit it, but that's mostly due to my limited availability, not because of your code. I think the tests that you are adding will be useful in the long term.

Welcome to the world of libraries and IT! There are not many of us using Go in library-land. If you haven't seen it, MIT also has done some related work: https://github.com/MITLibraries/fml

**Comment by blackerby** [comment]
Thanks so much for the quick response and the warm welcome. I've glanced at the MIT tool and will plan take a closer look.

No worries about looking in detail at an eventual PR any time soon. My hope is to put something together that will be easy to review if and when you have time.

By the way, I'm also working through your solr-for-newbies tutorial. It's excellent. Wish I could be in Princeton this year for the real thing!
